name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  flutter_lints: ^2.0.0
  flutter_riverpod: ^2.3.6
  flutter_test:
    sdk: flutter
  go_router: ^10.0.0
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - .env
